---
- setup:

- include_tasks: 
    file: preflight.yml

- include_tasks: 
    file: setup_hosts.yml
    apply:
      tags: hosts,elasticsearch
  tags: hosts,elasticsearch
  when: elasticsearch_resolv_mode == 'hosts'

- include_tasks: 
    file: install_elasticsearch.yml
    apply:
      tags: install,elasticsearch
  tags: install,elasticsearch
