---
dependencies: []

galaxy_info:
  description: 'Setup kibana'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - elk
    - kibana