---
dependencies: []

galaxy_info:
  description: 'Setup elk beats: filebeat, metricbeat, heartbeat'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - elk
    - beats
    - filebeat
    - metricbeat
    - heartbeat